# Generated by Django 4.0.6 on 2022-07-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFinancierMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('code_SFM', models.CharField(max_length=20, verbose_name='code lié au SFM')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='valeur')),
                ('details', models.TextField(verbose_name='details')),
            ],
        ),
    ]
