# Generated by Django 4.0.6 on 2022-07-19 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('depot_a_vue', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='depot a vue')),
                ('depot_a_terme', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='depot a terme')),
                ('titre_acquis', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='titre acquis')),
                ('total', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='total')),
            ],
        ),
    ]
