# Generated by Django 4.0.6 on 2022-07-19 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fraud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255, verbose_name='client id')),
                ('type_fraud', models.CharField(max_length=150, verbose_name='type de fraude')),
                ('date', models.DateField(auto_now=True)),
                ('nombre_transactions', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='nombre de transaction')),
                ('montant_transactions', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='montant transactions')),
                ('dispositif_gestion', models.TextField(verbose_name='dispositif de gestion')),
            ],
        ),
    ]
