# Generated by Django 4.1.1 on 2022-09-27 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControleMonetique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('valeur_initiale_monetique', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='valeur initial monnaie electronique en circulation')),
                ('nouvelle_emission_monetique', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='nouvelle emission de monnaie electronique')),
                ('destruction_monetique', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='destruction de monnaie electronique')),
                ('valeur_finale_totale_monetique', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='valeur finale totale de la monnaie electronique en circulation')),
                ('solde_compte_cantonnement', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='solde du compte de cantonnement')),
                ('solde_niveau_comptabilite', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='solde au niveau de la comptabilite')),
                ('nombre_transaction', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='nombre de transactions')),
                ('valeur_transaction', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='valeur des transactions')),
                ('date_operation', models.DateField(auto_now=True)),
                ('reference', models.CharField(max_length=255)),
                ('nature_operation', models.CharField(max_length=255)),
                ('montant', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('observations', models.TextField()),
            ],
        ),
    ]
