# Generated by Django 4.1.1 on 2022-09-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlemonetique',
            name='solde_total_comptes_cantonnement',
            field=models.IntegerField(blank=True, null=True, verbose_name='solde total des comptes de cantonnement'),
        ),
    ]
