# Generated by Django 4.1.1 on 2022-09-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetique', '0002_controlemonetique_solde_total_comptes_cantonnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlemonetique',
            name='solde_total_comptes_cantonnement',
            field=models.IntegerField(default=1, verbose_name='solde total des comptes de cantonnement'),
        ),
    ]
