# Generated by Django 4.1.1 on 2022-09-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetique', '0003_alter_controlemonetique_solde_total_comptes_cantonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlemonetique',
            name='ecart_comptabilite',
            field=models.IntegerField(blank=True, null=True, verbose_name='ecart comptabilite'),
        ),
        migrations.AddField(
            model_name='controlemonetique',
            name='ecart_comptabilite_compte_cantonnement',
            field=models.IntegerField(blank=True, null=True, verbose_name='ecart comptabilite comptabilite'),
        ),
        migrations.AddField(
            model_name='controlemonetique',
            name='ecart_compte_cantonnement',
            field=models.IntegerField(blank=True, null=True, verbose_name='ecart compte de cantonnement'),
        ),
        migrations.AlterField(
            model_name='controlemonetique',
            name='solde_total_comptes_cantonnement',
            field=models.IntegerField(default=0, verbose_name='solde total des comptes de cantonnement'),
        ),
    ]
