# Generated by Django 4.0.6 on 2022-07-19 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enregistrement', models.DateField(auto_now=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('severite', models.CharField(max_length=20, verbose_name='severite')),
                ('type_incident', models.CharField(max_length=255, verbose_name='type incident')),
                ('cause', models.CharField(max_length=255, verbose_name='cause')),
                ('impact', models.CharField(max_length=255, verbose_name='impacte')),
                ('solution', models.TextField(verbose_name='solution')),
                ('nombre_carte_capture', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nombre de carte capturée')),
                ('motif_capture', models.TextField(blank=True, null=True, verbose_name='motif de capture')),
                ('mesure_prise', models.TextField(blank=True, null=True, verbose_name='mesure prise')),
            ],
        ),
    ]
