# Generated by Django 4.0.6 on 2022-07-19 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicateurFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('code_indicateur', models.CharField(max_length=20, verbose_name='code indicateur')),
                ('indicateur', models.CharField(max_length=150, verbose_name='indicateur')),
                ('valeur', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='valeur')),
            ],
        ),
    ]
